import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Button, { ButtonProps } from "~/components/Button";

type ButtonHandler = React.MouseEventHandler<HTMLButtonElement>

const Calculator: NextPage = () => {
  const [display, setDisplay] = useState("");
  const [operation, setOperation] = useState("");
  const [float, setFloat] = useState(false);

  const handleNumClick: ButtonHandler = (e) => {
    console.log(`Clicked on: ${e.currentTarget.textContent}`)
    setDisplay(display + e.currentTarget.textContent)
  }

  const NumButton = ({ className, children }: ButtonProps) => {
    return <Button onClick={handleNumClick} className={className}>{children}</Button>
  }

  const handleOpClick: ButtonHandler = (e) => {
    console.log(`Set operation to: ${e.currentTarget.textContent}`);
    setOperation(e.currentTarget.textContent || "");
  }

  const OpButton = ({ children }: ButtonProps) => {
    return <Button onClick={handleOpClick} className="bg-orange-400 hover:bg-orange-300">{children}</Button>
  }

  const handleDotClick: ButtonHandler = () => {
    if (float) return;
    setDisplay(display + ".");
    setFloat(true);
  }

  const DotButton = ({ className, children }: ButtonProps) => {
    return <Button onClick={handleDotClick} className={className}>{children}</Button>
  } 

  return (
    <>
      <Head>
        <title>Calculator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-screen w-screen items-center justify-items-center font-mono">
        <div className="mx-auto w-96">
          <div className="grid grid-cols-4 gap-0 drop-shadow-lg">
            <h1 className="text-right text-white bg-neutral-500 p-4 text-2xl col-span-4 rounded-t-lg">
              {display === "" ? "0" : display}
            </h1>
            <Button className="col-span-3">C</Button>
            <OpButton>/</OpButton>
            <NumButton>7</NumButton>
            <NumButton>8</NumButton>
            <NumButton>9</NumButton>
            <OpButton>x</OpButton>
            <NumButton>4</NumButton>
            <NumButton>5</NumButton>
            <NumButton>6</NumButton>
            <OpButton>-</OpButton>
            <NumButton>1</NumButton>
            <NumButton>2</NumButton>
            <NumButton>3</NumButton>
            <OpButton>+</OpButton>
            <NumButton className="col-span-2 rounded-bl-lg">0</NumButton>
            <DotButton>.</DotButton>
            <Button className="rounded-br-lg">=</Button>
          </div>
        </div>
      </div>
    </>
  );
};

export default Calculator;
